# Generated by Django 3.1 on 2020-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
